backend:
  name: git-gateway # 使用 Netlify 的 Git Gateway 进行认证和 API 访问
  branch: main # 或者您的主分支名称，例如 master

media_folder: "public/uploads" # 媒体文件存储在仓库的这个目录下
public_folder: "/uploads" # 媒体文件在网站上的访问路径
# 添加 media_library
media_library:
  name: 'git-gateway'

# 添加本地化配置
locale: "zh_Hans"

# 添加发布工作流配置
publish_mode: "editorial_workflow"

collections:
  - name: "posts" # 将 name 从 blog 改为 posts
    label: "博客文章" # 将 label 从 Blog 改为 博客文章
    folder: "src/content/posts" # 将 folder 路径改为 posts
    create: true # 允许在 CMS 中创建新文章
    slug: "{{slug}}" # 简化文件名格式
    fields: # 定义文章包含的字段
      - {label: "标题", name: "title", widget: "string"}
      - {label: "URL路径", name: "slug", widget: "string", hint: "自定义文章的URL路径。如不填写，将自动使用日期时间+标题中的英文单词组合（例如：20230815123045-vibe-coding）", required: false}
      - {label: "发布日期", name: "publishDate", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "摘要", name: "excerpt", widget: "text", required: false}
      - {label: "特色图片", name: "featuredImage", widget: "image", required: false}
      - {label: "标签", name: "tags", widget: "list", required: false}
      - {label: "内容", name: "body", widget: "markdown"}

  # 添加静态页面集合
  - name: "pages"
    label: "静态页面"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "URL路径", name: "slug", widget: "string", hint: "自定义页面的URL路径。如不填写，将使用文件名", required: false}
      - {label: "内容", name: "body", widget: "markdown"}

  # 添加站点配置集合
  - name: "config"
    label: "网站配置"
    files:
      - label: "基本配置"
        name: "config"
        file: "src/content/config.json"
        fields:
          - {label: "网站标题", name: "title", widget: "string"}
          - {label: "网站描述", name: "description", widget: "text"}
          - {label: "作者", name: "author", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image", required: false}
          - {label: "网站图标", name: "favicon", widget: "string", required: false}
          - {label: "管理页面URL", name: "adminUrl", widget: "string", hint: "请填写您的Netlify站点管理地址，如: https://your-site.netlify.app/admin/", required: false}
          - label: "社交媒体"
            name: "social"
            widget: "object"
            fields:
              - {label: "GitHub", name: "github", widget: "string", required: false}
              - {label: "Twitter", name: "twitter", widget: "string", required: false}
              - {label: "微博", name: "weibo", widget: "string", required: false}
              - {label: "知乎", name: "zhihu", widget: "string", required: false}
      
      - label: "友情链接"
        name: "links"
        file: "src/content/links.json"
        fields:
          - label: "链接"
            name: "links"
            widget: "list"
            fields:
              - {label: "名称", name: "name", widget: "string"}
              - {label: "网址", name: "url", widget: "string"}
              - {label: "描述", name: "description", widget: "text", required: false}
              - {label: "图标", name: "icon", widget: "string", required: false}
